# 网站标题
logo_title: WannaYoung

# 配色（white|black）
style: white

# 网站icon
favicon: /favicon.ico

# 菜单栏
menu:
  软件: /soft
  友链: /links
  关于: /about
  Github: https://github.com/WannaYoung

# Valine评论
valine:
  appId: EsjB0IljIqxRoDlvBL0tEQaU-gzGzoHsz
  appKey: jxkFp5G2GF0GykN6miPGTskw

# 禁用自带代码高亮
highlight:
  enable: false